[menu __main machine_tools]
name: Machine Tools
icon: settings

[menu __main machine_tools box_small]
name: Box Small
icon: fine_tune
method: printer.gcode.script
params: {"script":"BOX_SMALL"}

[menu __main machine_tools box_medium]
name: Box Medium
icon: fine_tune
method: printer.gcode.script
params: {"script":"BOX_MEDIUM"}

[menu __main machine_tools box_large]
name: Box Large
icon: fine_tune
method: printer.gcode.script
params: {"script":"BOX_LARGE"}

[menu __main machine_tools clear_box]
name: Clear Box
icon: cancel
method: printer.gcode.script
params: {"script":"CLEAR_BOX_SELECTION"}

[menu __main machine_tools home_all_custom]
name: Home / Init
icon: home
method: printer.gcode.script
params: {"script":"HOME_ALL_CUSTOM"}

[menu __main machine_tools left]
name: Left
icon: left
method: printer.gcode.script
params: {"script":"LEFT DIST=10"}

[menu __main machine_tools right]
name: Right
icon: right
method: printer.gcode.script
params: {"script":"RIGHT DIST=10"}

[menu __main machine_tools forward]
name: Forward
icon: up
method: printer.gcode.script
params: {"script":"FORWARD DIST=10"}

[menu __main machine_tools backward]
name: Backward
icon: down
method: printer.gcode.script
params: {"script":"BACKWARD DIST=10"}

[menu __main machine_tools up]
name: Up
icon: increase
method: printer.gcode.script
params: {"script":"UP DIST=5"}

[menu __main machine_tools down]
name: Down
icon: decrease
method: printer.gcode.script
params: {"script":"DOWN DIST=5"}

[menu __main machine_tools yaw_left]
name: Yaw Left
icon: refresh
method: printer.gcode.script
params: {"script":"YAW_LEFT ANGLE=10"}

[menu __main machine_tools yaw_right]
name: Yaw Right
icon: refresh
method: printer.gcode.script
params: {"script":"YAW_RIGHT ANGLE=10"}

[menu __main machine_tools eof_open]
name: EOF Open
icon: extrude
method: printer.gcode.script
params: {"script":"EOF_OPEN DIST=20"}

[menu __main machine_tools eof_close]
name: EOF Close
icon: retract
method: printer.gcode.script
params: {"script":"EOF_CLOSE"}

[menu __main machine_tools resume]
name: Resume
icon: resume
method: printer.gcode.script
params: {"script":"SAFETY_RESUME"}
#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# 
#~#
